### ISSUE TITLE
Investigate issues with mixed repodata

### ISSUE THREAD

**Issue by jezdez** [conda/conda-index#89]
### What happened?

A few recipes have seen repodata files where the subdir doesn't match some of the packages listed in them:

- https://github.com/conda-forge/python-feedstock/pull/610
- https://github.com/conda-forge/jupyter_server-feedstock/issues/111
- https://github.com/conda-forge/conda-feedstock/pull/197

I'm wondering if this is related to conda-index and thought to file a ticket here to investigate.

**Comment by mbargull** [comment]
This comes from https://github.com/openSUSE/libsolv/commit/cc2da2e789f651b2d0d55fe31c258426bf9e984d#diff-2f0af950e6d2249e0340147b80f5b8194de5362f23026ff65cdb65dfa57696aaR314-R320 , i.e., a newly added strict check in `libsolv=0.7.23` update.
That check is probably reasonable/good -- but `conda-build` is not so strict and dumps the to-be-downstream-tested packages in the current subdir.
I'll open an issue on `conda-build` and -- to get things working for now -- a PR to add a constraint for `libsolv` in the `boa-feedstock` (because it's technically an incompatibility between `conda-build` and `libsolv` which manifests in plumbing, i.e., `boa`/`conda-mambabuild`).

**Comment by mbargull** [comment]
refs:
 - https://github.com/conda/conda-build/issues/4750
 - https://github.com/conda-forge/boa-feedstock/pull/61

**Comment by jezdez** [comment]
Thanks @mbargull!

**Comment by kenodegard** [comment]
Closing since the issue is with conda-build itself (see https://github.com/conda/conda-build/pull/4763)
